version: '3.0'
services:
  db:
    image: postgres:latest
    env_file: .env
    ports:
      - 5555:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data: