version: '3.0'
services:
  db:
    image: postgres:latest
    env_file: .env
    ports:
      - 5555:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    restart: always


volumes:
  pg_data:
  redis:
