# Generated by Django 5.0.1 on 2024-01-17 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False, verbose_name='company_id')),
                ('company_name', models.CharField(max_length=200, verbose_name='company_name')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ('company_id',),
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False, verbose_name='file_id')),
                ('file_name', models.CharField(max_length=100, verbose_name='file_name')),
                ('file_link', models.URLField(max_length=5000, verbose_name='file_link')),
                ('file_type', models.CharField(max_length=10, verbose_name='file_type')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ('file_id',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False, verbose_name='task_id')),
                ('task_name', models.CharField(max_length=150, verbose_name='task_name')),
                ('task_description', models.CharField(max_length=10000, verbose_name='task_description')),
                ('task_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Need Details', 'Need Details'), ('Reassigned', 'Reassigned'), ('Review', 'Review'), ('Hold', 'Hold'), ('Closed', 'Closed')], default='Open', max_length=40, verbose_name='task_status')),
                ('task_start_date', models.DateTimeField(verbose_name='task_start_date')),
                ('task_end_date_plan', models.DateTimeField(blank=True, verbose_name='task_end_date_plan')),
                ('task_end_date_fact', models.DateTimeField(blank=True, null=True, verbose_name='task_end_date_plan')),
                ('task_note_employee', models.CharField(max_length=10000, verbose_name='task_note_employee')),
                ('task_note_cheif', models.CharField(max_length=10000, verbose_name='task_note_cheif')),
                ('task_note_mentor', models.CharField(max_length=10000, verbose_name='task_note_mentor')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ('task_id',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False, verbose_name='dep_id')),
                ('dep_name', models.CharField(max_length=400, verbose_name='dep_name')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idp_app.company', verbose_name='company_id')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departmens',
                'ordering': ('dep_id',),
            },
        ),
    ]
