# Generated by Django 5.0.1 on 2024-01-17 11:09

import datetime
import django.db.models.deletion
import idp_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDP',
            fields=[
                ('idp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='idp_id')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('target', models.TextField(blank=True, max_length=255, null=True, verbose_name='target')),
                ('status', models.CharField(choices=[('active', 'Активные'), ('completed', 'Выполненные'), ('two_weeks', 'Две недели до плановой даты выполнения'), ('overdue', 'Просроченные'), ('canceled', 'Отмененные'), ('closed', 'Закрытые'), ('draft', 'Черновик')], default='draft', max_length=255, verbose_name='status')),
                ('start_date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='start_date')),
                ('end_date_plan', models.DateField(blank=True, default=idp_app.models.default_end_date_plan, null=True, verbose_name='end_date_plan')),
                ('end_date_fact', models.DateField(blank=True, null=True, verbose_name='end_date_fact')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
