# Generated by Django 5.0.1 on 2024-01-28 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_file', to='idp_app.task', verbose_name='file_task'),
        ),
    ]
