# Generated by Django 5.0.1 on 2024-01-25 10:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idp',
            options={'ordering': ('name', 'start_date'), 'verbose_name': 'IDP', 'verbose_name_plural': 'IDPs'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('name',), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='task',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='mentor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_end_date_plan',
            field=models.DateTimeField(blank=True, null=True, verbose_name='task_end_date_plan'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_note_cheif',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='task_note_cheif'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_note_employee',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='task_note_employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_start_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='task_start_date'),
        ),
    ]
