# Generated by Django 5.0.1 on 2024-01-24 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idp',
            options={'ordering': ('name', 'start_date'), 'verbose_name': 'IDP', 'verbose_name_plural': 'IDPs'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('name',), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='idpnotification',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idp_notices', to=settings.AUTH_USER_MODEL, verbose_name='receiver_of_notice'),
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_notices', to=settings.AUTH_USER_MODEL, verbose_name='receiver_of_notice'),
        ),
        migrations.AlterField(
            model_name='idp',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('draft_approval', 'Черновик (на согласовании)'), ('active', 'Активные (в работе)'), ('two_weeks', 'Две недели до плановой даты выполнения'), ('overdue', 'Просрочено'), ('cancelled', 'Отменено'), ('completed_approval', 'Выполнено (на подтверждении)'), ('closed', 'Выполнено')], default='draft', max_length=255, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='trigger',
            field=models.CharField(choices=[('Idp_created', 'Idp Created'), ('Task_created', 'Task Created'), ('Task_created_with_idp', 'Task Created With Idp'), ('Idp_updated', 'Idp Updated'), ('Idp_comment_added', 'Task Comment Added'), ('Idp_task_updated', 'Task Updated'), ('Task_enddate_plan_updated', 'Task Enddate Updated'), ('Mentor_changed', 'Mentor Changed'), ('Two_weeks_before_idp_overdue', 'Idp Two Weeks'), ('Idp_overdue', 'Idp Overdue'), ('Idp_request_from_employee', 'Idp Request Created'), ('Idp_cancelled', 'Idp Cancelled'), ('Idp_close_request_created', 'Idp Completed Approval'), ('Idp_close_request_accepted', 'Idp Closed'), ('Idp_close_request_rejected', 'Idp Close Rejected'), ('Idp_request_rejected', 'Idp Request Rejected'), ('Two_weeks_before_task_overdue', 'Task Two Weeks'), ('Task_overdue', 'Task Overdue'), ('Task_cancelled', 'Task Cancelled'), ('Task_cancelled_because_of_idp', 'Task Cancelled After Idp'), ('Task_close_request_created', 'Task Completed Approval'), ('Task_closed', 'Task Closed'), ('Task_close_rejected', 'Task Close Rejected')], default='Idp_created', max_length=255, verbose_name='notification_trigger'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_note_cheif',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='task_note_cheif'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_note_employee',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='task_note_employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_note_mentor',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='task_note_mentor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('draft_approval', 'Черновик (на согласовании)'), ('active', 'Активные (в работе)'), ('active_with_idp', 'Активные (в работе)'), ('two_weeks', 'Две недели до плановой даты выполнения'), ('overdue', 'Просрочено'), ('cancelled', 'Отменено'), ('cancelled_with_idp', 'Отменено'), ('completed_approval', 'Выполнено (на подтверждении)'), ('rejected', 'Активные (в работе)'), ('closed', 'Выполнено')], default='draft', max_length=40, verbose_name='task_status'),
        ),
    ]
