# Generated by Django 5.0.1 on 2024-01-17 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idp_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_mentor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_tasks', to=settings.AUTH_USER_MODEL, verbose_name='task_mentor_id'),
        ),
        migrations.AddField(
            model_name='file',
            name='file_task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idp_app.task', verbose_name='file_task_id'),
        ),
    ]
