# Generated by Django 5.0.1 on 2024-01-17 16:30

import core.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idp',
            name='end_date_fact',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end_date_fact'),
        ),
        migrations.AlterField(
            model_name='idp',
            name='end_date_plan',
            field=models.DateTimeField(blank=True, default=core.utils.default_end_date_plan, null=True, verbose_name='end_date_plan'),
        ),
        migrations.AlterField(
            model_name='idp',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='start_date'),
        ),
    ]
