# Generated by Django 5.0.1 on 2024-01-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_app', '0002_idp_is_draft_idp_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idp',
            name='is_draft',
        ),
        migrations.AlterField(
            model_name='idp',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Two weeks', 'Two Weeks'), ('Overdue', 'Overdue'), ('Canceled', 'Canceled'), ('Closed', 'Closed'), ('Draft', 'Draft')], default='Draft', max_length=255, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Two weeks', 'Two Weeks'), ('Overdue', 'Overdue'), ('Canceled', 'Canceled'), ('Closed', 'Closed'), ('Draft', 'Draft')], default='Open', max_length=40, verbose_name='task_status'),
        ),
    ]
